# Generated by Django 5.2.6 on 2025-09-19 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(help_text='The order in which the question appears.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the questionnaire (e.g., HADS)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The official name of the study.', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Studies',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('value', models.IntegerField(help_text='The score/value for this choice.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='study.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='study.questionnairetemplate'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(blank=True, help_text='Unique, anonymized identifier for the participant.', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('SCREENING', 'Screening'), ('ELIGIBLE', 'Eligible'), ('ENROLLED', 'Enrolled'), ('WITHDRAWN', 'Withdrawn'), ('COMPLETED', 'Completed')], default='SCREENING', max_length=20)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('assigned_group_name', models.CharField(blank=True, help_text="Name of the assigned group, e.g., 'Intervention' or 'Control'", max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='study.study')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('BASELINE', 'Baseline Visit'), ('VISIT1', 'Visit 1 (6-Month)'), ('VISIT2', 'Visit 2 (12-Month)'), ('EXIT', 'Exit Visit')], max_length=20)),
                ('visit_date', models.DateField()),
                ('is_complete', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='study.participant')),
            ],
            options={
                'unique_together': {('participant', 'visit_type')},
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MLHF', 'Minnesota Living with Heart Failure'), ('EQ-5D-5L', 'Quality of Life (EQ-5D-5L)'), ('HADS', 'Hospital Anxiety and Depression Scale'), ('FAQ', 'Functional Assessment Questionnaire'), ('MIDI', 'Measurement Instrument for Determinants of Innovations')], max_length=10)),
                ('results', models.JSONField(blank=True, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='study.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Neuroimaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mri_completed', models.BooleanField(default=False, verbose_name='Research MRI Completed')),
                ('mri_report', models.FileField(blank=True, null=True, upload_to='mri_reports/')),
                ('mri_key_findings', models.TextField(blank=True, null=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neuroimaging', to='study.visit')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moca_score', models.IntegerField(blank=True, null=True, verbose_name='Montreal Cognitive Assessment (MoCA) score')),
                ('ntb_results_summary', models.TextField(blank=True, null=True, verbose_name='Neuropsychological Test Battery (NTB) Results')),
                ('nyha_class', models.CharField(blank=True, max_length=10, null=True, verbose_name='NYHA classification')),
                ('six_minute_walk_test_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='6-minute walk test (meters)')),
                ('tug_test_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Timed up-and-go (TUG) test (seconds)')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_assessment', to='study.visit')),
            ],
        ),
        migrations.CreateModel(
            name='BiologicalSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_blood_screening_summary', models.TextField(blank=True, help_text='B12, folate, thyroid, liver, kidney function', null=True)),
                ('gfap', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='GFAP')),
                ('nfl', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='NfL')),
                ('abeta40_42_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Abeta40/42 Ratio')),
                ('ptau217', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='ptau217')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biological_sample', to='study.visit')),
            ],
        ),
        migrations.CreateModel(
            name='VisitAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('questionnaire_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.questionnairetemplate')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='study.visit')),
            ],
            options={
                'unique_together': {('visit', 'questionnaire_template')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.question')),
                ('visit_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='study.visitassessment')),
            ],
        ),
        migrations.CreateModel(
            name='WearableDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('hrv', models.IntegerField(blank=True, null=True, verbose_name='Heart Rate Variability')),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('spo2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='SpO2')),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('steps_count', models.IntegerField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_data', to='study.participant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
