# Generated by Django 5.2.6 on 2025-09-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalsample',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clinicalassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='neuroimaging',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
